context:
  version: "0.5.0"

package:
  name: fans-dashboard
  version: ${{ version }}

source:
  url: https://github.com/DataAnalyticsEngineering/FANS/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 0016c60b770e384cd52ae423e906ceddac0654049994a84678571ab9a42fdb63

build:
  noarch: python
  script: python -m pip install ./FANS_Dashboard -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - numpy
    - h5py
    - plotly
    - lxml
    - scipy
    - meshio

tests:
  - python:
      imports:
        - fans_dashboard
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/DataAnalyticsEngineering/FANS
  summary: "FANS-Dashboard: pure python utilities for FANS, the open-source, efficient, and parallel FFT-based homogenization solver designed to solve microscale multiphysics problems."
  description: |
    The FANS Dashboard is a comprehensive tool designed to streamline the post-processing, interpretation, and visualization of results generated by the FANS solver. The library provides a user-friendly environment to work with complex simulation data stored in HDF5 format, offering a step-by-step workflow that covers data extraction, postprocessing, visualization, and preparation for 3D visualization in tools like ParaView.
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sanathkeshav
    - claudiushaag
